### ISSUE TITLE
Which additional libraries are needed for this driver pack to work?

### ISSUE THREAD

**Issue by RobertMouncer** [SeeedJP/GroveDriverPack#5]
When running the examples I have imported the WioLTEforArduino library but am still getting this error:
```
GrovePM25HM3301:26:3: error: 'Board' was not declared in this scope

   Board.I2C.Enable();

   ^

exit status 1
'GroveBoard' does not name a type
```

Is this due to a library not being imported?

**Comment by matsujirushi** [comment]
Did you use latest package and library?

Package ... SeeedJP STM32 Boards v1.3.0
Library ... Wio LTE for Arduino by Seeed K.K. v2.10.0

Package index is here.
https://www.seeed.co.jp/package_SeeedJP_index.json

**Comment by matsujirushi** [comment]
# Package

![image](https://user-images.githubusercontent.com/8079404/80366465-44f38900-88c4-11ea-8493-060c6886b9c0.png)

# Library

![image](https://user-images.githubusercontent.com/8079404/80366511-5d63a380-88c4-11ea-9f3d-60fb8dd17858.png)

**Comment by RobertMouncer** [comment]
Thank you I was using a package provided different STM32 package provided by seeed.

I am now able to compile.
